import type { Metadata } from "next";
import "./landing.css";
import Link from "next/link";
import Logo from "@/components/ui/logo";

export const metadata: Metadata = {
	title: "Pay with Crypto",
	description: "Generated by create next app",
};

type IProps = Readonly<{ children: React.ReactNode }>

export default function RootLayout({ children }: IProps) {
	return <html>
		<body>

			<nav>
				<Logo />
				<div>
					<Link href="/about">About us</Link>
					<Link href="/how-it-works">How it works</Link>
					<Link href="/pricing">Pricing</Link>
				</div>
				<div>
					<button>
						<Link href="/dashboard">Dashboard</Link>
					</button>
				</div>
			</nav>

			<main>
				{children}
			</main>
		</body>
	</html>
}
