import type { Metadata } from "next";
import './payment.css'
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { Container } from "@mui/material";
import FeedbackToast from "@/components/dashboard/feedback-toast";

export const metadata: Metadata = {
	title: "Pay with Crypto",
	description: "Generated by create next app",
};

type IProps = Readonly<{ children: React.ReactNode }>

export default async function PaymentLayout({ children }: IProps) {
	return <html>
		<body>
			<AppRouterCacheProvider>
				<main>
					<Container sx={{ marginTop: '10vh' }}>
						{children}
					</Container>
				</main>
				<FeedbackToast />
			</AppRouterCacheProvider>
		</body>
	</html>
}
