import type { Metadata } from "next";
import "./landing.css";

export const metadata: Metadata = {
	title: "Pay with Crypto",
	description: "Generated by create next app",
};

type IProps = Readonly<{ children: React.ReactNode }>

export default function RootLayout({ children }: IProps) {
	return <html>
		<body>
			{children}
		</body>
	</html>
}
